# Generated by https://github.com/jiro4989/nimjson

type
  # NilType* = ref object
  IgPost* = ref object
    commentLikesEnabled*: bool
    comments*: seq[IgPostComments]
    commentCount*: int64
    caption*: IgPostCaption
    captionIsEdited*: bool
    hasMoreComments*: bool
    hasMoreHeadloadComments*: bool
    likedByMediaOwnerBadgeEnabled*: bool
    previewComments*: seq[IgPostIgPostPreviewComments]
    threadingEnabled*: bool
    mediaHeaderDisplay*: string
    initiateAtTop*: bool
    insertNewCommentToTop*: bool
    quickResponseEmojis*: seq[IgPostQuickResponseEmojis]
    canViewMorePreviewComments*: bool
    scrollBehavior*: int64
    commentCoverPos*: string
    isRanked*: bool
    commentFilterParam*: string
    status*: string
    message*: string ## Error message
  IgPostComments* = ref object
    hasLikedComment*: bool
    commentLikeCount*: int64
    childCommentCount*: int64
    previewChildComments*: seq[IgPostPreviewChildComments]
    otherPreviewUsers*: seq[IgPostOtherPreviewUsers]
    nextMaxChildCursor*: string
    hasMoreTailChildComments*: bool
    nextMinChildCursor*: string
    hasMoreHeadChildComments*: bool
    numTailChildComments*: int64
    numHeadChildComments*: int64
    pk*: string
    userId*: string
    `type`*: int64
    didReportAsSpam*: bool
    createdAt*: int64
    createdAtUtc*: int64
    contentType*: string
    status*: string
    bitFlags*: int64
    shareEnabled*: bool
    isRankedComment*: bool
    mediaId*: string
    commentIndex*: int64
    user*: IgPostUser2
    text*: string
    isCovered*: bool
    privateReplyStatus*: int64
    inlineComposerDisplayCondition*: string
  IgPostPreviewChildComments* = ref object
    contentType*: string
    user*: IgPostUser
    pk*: string
    text*: string
    `type`*: int64
    createdAt*: int64
    createdAtUtc*: int64
    mediaId*: string
    status*: string
    parentCommentId*: string
    shareEnabled*: bool
    privateReplyStatus*: int64
    childCommentIndex*: int64
    hasLikedComment*: bool
    commentLikeCount*: int64
    commentHasAVisualReplyMedia*: bool
    # mediaInfo*: NilType
  IgPostUser* = ref object
    fbidV2*: string
    pk*: string
    pkId*: string
    fullName*: string
    isPrivate*: bool
    thirdPartyDownloadsEnabled*: int64
    hasAnonymousProfilePicture*: bool
    isMentionable*: bool
    username*: string
    isVerified*: bool
    profilePicId*: string
    profilePicUrl*: string
    # accountBadges*: seq[NilType]
  IgPostOtherPreviewUsers* = ref object
    id*: string
    profilePicUrl*: string
  IgPostUser2* = ref object
    pk*: string
    pkId*: string
    fullName*: string
    isPrivate*: bool
    fbidV2*: string
    username*: string
    isMentionable*: bool
    isVerified*: bool
    profilePicId*: string
    profilePicUrl*: string
    latestReelMedia*: int64
    latestBestiesReelMedia*: int64
  IgPostCaption* = ref object
    pk*: string
    userId*: string
    `type`*: int64
    didReportAsSpam*: bool
    createdAt*: int64
    createdAtUtc*: int64
    contentType*: string
    status*: string
    bitFlags*: int64
    shareEnabled*: bool
    isRankedComment*: bool
    mediaId*: string
    user*: IgPostUser3
    text*: string
    isCovered*: bool
    privateReplyStatus*: int64
    isCreatedByMediaOwner*: bool
  IgPostUser3* = ref object
    pk*: string
    pkId*: string
    fullName*: string
    isPrivate*: bool
    fbidV2*: string
    username*: string
    isMentionable*: bool
    fanClubStatusSyncInfo*: IgPostFanClubStatusSyncInfo
    isVerified*: bool
    profilePicId*: string
    profilePicUrl*: string
  IgPostFanClubStatusSyncInfo* = ref object
    subscribed*: bool
    eligibleToSubscribe*: bool
  IgPostIgPostPreviewComments* = ref object
    hasLikedComment*: bool
    commentLikeCount*: int64
    pk*: string
    userId*: string
    `type`*: int64
    didReportAsSpam*: bool
    createdAt*: int64
    createdAtUtc*: int64
    contentType*: string
    status*: string
    bitFlags*: int64
    shareEnabled*: bool
    isRankedComment*: bool
    mediaId*: string
    parentCommentId*: string
    user*: IgPostUser4
    text*: string
    isCovered*: bool
    privateReplyStatus*: int64
    isCreatedByMediaOwner*: bool
  IgPostUser4* = ref object
    pk*: string
    pkId*: string
    fullName*: string
    isPrivate*: bool
    fbidV2*: string
    username*: string
    isMentionable*: bool
    isVerified*: bool
    profilePicId*: string
    profilePicUrl*: string
    latestReelMedia*: int64
    latestBestiesReelMedia*: int64
  IgPostQuickResponseEmojis* = ref object
    unicode*: string
