# Generated by https://github.com/jiro4989/nimjson

type
  # NilType* = ref object
  Post* = ref object
    commentLikesEnabled*: bool
    comments*: seq[Comments]
    commentCount*: int64
    caption*: Caption
    captionIsEdited*: bool
    hasMoreComments*: bool
    hasMoreHeadloadComments*: bool
    likedByMediaOwnerBadgeEnabled*: bool
    previewComments*: seq[PreviewComments]
    threadingEnabled*: bool
    mediaHeaderDisplay*: string
    initiateAtTop*: bool
    insertNewCommentToTop*: bool
    quickResponseEmojis*: seq[QuickResponseEmojis]
    canViewMorePreviewComments*: bool
    scrollBehavior*: int64
    commentCoverPos*: string
    isRanked*: bool
    commentFilterParam*: string
    status*: string
  Comments* = ref object
    hasLikedComment*: bool
    commentLikeCount*: int64
    childCommentCount*: int64
    previewChildComments*: seq[PreviewChildComments]
    otherPreviewUsers*: seq[OtherPreviewUsers]
    nextMaxChildCursor*: string
    hasMoreTailChildComments*: bool
    nextMinChildCursor*: string
    hasMoreHeadChildComments*: bool
    numTailChildComments*: int64
    numHeadChildComments*: int64
    pk*: string
    userId*: string
    `type`*: int64
    didReportAsSpam*: bool
    createdAt*: int64
    createdAtUtc*: int64
    contentType*: string
    status*: string
    bitFlags*: int64
    shareEnabled*: bool
    isRankedComment*: bool
    mediaId*: string
    commentIndex*: int64
    user*: User2
    text*: string
    isCovered*: bool
    privateReplyStatus*: int64
    inlineComposerDisplayCondition*: string
  PreviewChildComments* = ref object
    contentType*: string
    user*: User
    pk*: string
    text*: string
    `type`*: int64
    createdAt*: int64
    createdAtUtc*: int64
    mediaId*: string
    status*: string
    parentCommentId*: string
    shareEnabled*: bool
    privateReplyStatus*: int64
    childCommentIndex*: int64
    hasLikedComment*: bool
    commentLikeCount*: int64
    commentHasAVisualReplyMedia*: bool
    # mediaInfo*: NilType
  User* = ref object
    fbidV2*: string
    pk*: string
    pkId*: string
    fullName*: string
    isPrivate*: bool
    thirdPartyDownloadsEnabled*: int64
    hasAnonymousProfilePicture*: bool
    isMentionable*: bool
    username*: string
    isVerified*: bool
    profilePicId*: string
    profilePicUrl*: string
    # accountBadges*: seq[NilType]
  OtherPreviewUsers* = ref object
    id*: string
    profilePicUrl*: string
  User2* = ref object
    pk*: string
    pkId*: string
    fullName*: string
    isPrivate*: bool
    fbidV2*: string
    username*: string
    isMentionable*: bool
    isVerified*: bool
    profilePicId*: string
    profilePicUrl*: string
    latestReelMedia*: int64
    latestBestiesReelMedia*: int64
  Caption* = ref object
    pk*: string
    userId*: string
    `type`*: int64
    didReportAsSpam*: bool
    createdAt*: int64
    createdAtUtc*: int64
    contentType*: string
    status*: string
    bitFlags*: int64
    shareEnabled*: bool
    isRankedComment*: bool
    mediaId*: string
    user*: User3
    text*: string
    isCovered*: bool
    privateReplyStatus*: int64
    isCreatedByMediaOwner*: bool
  User3* = ref object
    pk*: string
    pkId*: string
    fullName*: string
    isPrivate*: bool
    fbidV2*: string
    username*: string
    isMentionable*: bool
    fanClubStatusSyncInfo*: FanClubStatusSyncInfo
    isVerified*: bool
    profilePicId*: string
    profilePicUrl*: string
  FanClubStatusSyncInfo* = ref object
    subscribed*: bool
    eligibleToSubscribe*: bool
  PreviewComments* = ref object
    hasLikedComment*: bool
    commentLikeCount*: int64
    pk*: string
    userId*: string
    `type`*: int64
    didReportAsSpam*: bool
    createdAt*: int64
    createdAtUtc*: int64
    contentType*: string
    status*: string
    bitFlags*: int64
    shareEnabled*: bool
    isRankedComment*: bool
    mediaId*: string
    parentCommentId*: string
    user*: User4
    text*: string
    isCovered*: bool
    privateReplyStatus*: int64
    isCreatedByMediaOwner*: bool
  User4* = ref object
    pk*: string
    pkId*: string
    fullName*: string
    isPrivate*: bool
    fbidV2*: string
    username*: string
    isMentionable*: bool
    isVerified*: bool
    profilePicId*: string
    profilePicUrl*: string
    latestReelMedia*: int64
    latestBestiesReelMedia*: int64
  QuickResponseEmojis* = ref object
    unicode*: string
