# Generated by https://github.com/jiro4989/nimjson

from std/options import Option

type
  # IgUserNilType* = ref object
  IgUserResponse* = ref object
    data*: IgUserData
    status*: string
    message*: string ## Error message
  IgUserData = ref object
    user*: IgUser
  IgUser* = ref object
    status*: string
    message*: string ## Error message
    biography*: string
    bioLinks*: seq[IgUserBioLinks]
    # fbProfileBiolink*: NilType
    biographyWithEntities*: IgUserBiographyWithEntities
    blockedByViewer*: bool
    restrictedByViewer*: Option[bool]
    countryBlock*: bool
    eimuId*: string
    externalUrl*: string
    # externalUrlLinkshimmed*: string
    edgeFollowedBy*: IgUserEdgeFollowedBy
    fbid*: string
    followedByViewer*: bool
    edgeFollow*: IgUserEdgeFollow
    followsViewer*: bool
    fullName*: string
    # groupMetadata*: NilType
    hasArEffects*: bool
    hasClips*: bool
    hasGuides*: bool
    hasChannel*: bool
    hasBlockedViewer*: bool
    highlightReelCount*: int64
    hasRequestedViewer*: bool
    hideLikeAndViewCounts*: bool
    id*: string
    isBusinessAccount*: bool
    isProfessionalAccount*: bool
    isSupervisionEnabled*: bool
    isGuardianOfViewer*: bool
    isSupervisedByViewer*: bool
    isSupervisedUser*: bool
    isEmbedsDisabled*: bool
    isJoinedRecently*: bool
    # guardianId*: NilType
    # businessAddressJson*: NilType
    businessContactMethod*: string
    # businessEmail*: NilType
    # businessPhoneNumber*: NilType
    businessCategoryName*: string
    # overallCategoryName*: NilType
    categoryEnum*: string
    categoryName*: string
    isPrivate*: bool
    isVerified*: bool
    isVerifiedByMv4b*: bool
    isRegulatedC18*: bool
    edgeMutualFollowedBy*: IgUserEdgeMutualFollowedBy
    pinnedChannelsListCount*: int64
    profilePicUrl*: string
    profilePicUrlHd*: string
    requestedByViewer*: bool
    shouldShowCategory*: bool
    shouldShowPublicContacts*: bool
    showAccountTransparencyDetails*: bool
    # transparencyLabel*: NilType
    transparencyProduct*: string
    username*: string
    connectedFbPage*: string # Not sure
    # pronouns*: seq[NilType]
    edgeFelixVideoTimeline*: IgUserEdgeFelixVideoTimeline
    edgeOwnerToTimelineMedia*: IgUserEdgeOwnerToTimelineMedia
    edgeSavedMedia*: IgUserEdgeSavedMedia
    edgeMediaCollections*: IgUserEdgeMediaCollections
    edgeRelatedProfiles*: IgUserEdgeRelatedProfiles
  IgUserBioLinks* = ref object
    title*: string
    lynxUrl*: string
    url*: string
    linkType*: string
  IgUserBiographyWithEntities* = ref object
    rawText*: string
    # entities*: seq[NilType]
  IgUserEdgeFollowedBy* = ref object
    count*: int64
  IgUserEdgeFollow* = ref object
    count*: int64
  IgUserEdgeMutualFollowedBy* = ref object
    count*: int64
    # edges*: seq[NilType]
  IgUserEdgeFelixVideoTimeline* = ref object
    count*: int64
    pageInfo*: IgUserPageInfo
    edges*: seq[IgUserEdges] ## Posts
  IgUserPageInfo* = ref object
    hasNextPage*: bool
    endCursor*: string
  IgUserEdges* = ref object
    node*: IgUserNode
  IgUserNode* = ref object
    typename*: string
    id*: string
    shortcode*: string
    dimensions*: IgUserDimensions
    displayUrl*: string
    edgeMediaToTaggedUser*: IgUserEdgeMediaToTaggedUser
    # factCheckOverallRating*: NilType
    # factCheckInformation*: NilType
    # gatingInfo*: NilType
    sharingFrictionInfo*: IgUserSharingFrictionInfo
    # mediaOverlayInfo*: NilType
    mediaPreview*: string
    owner*: IgUserOwner
    isVideo*: bool
    hasUpcomingEvent*: bool
    # accessibilityCaption*: NilType
    dashInfo*: IgUserDashInfo
    hasAudio*: bool
    trackingToken*: string
    videoUrl*: string
    videoViewCount*: int64
    edgeMediaToCaption*: IgUserEdgeMediaToCaption
    edgeMediaToComment*: IgUserEdgeMediaToComment
    commentsDisabled*: bool
    takenAtTimestamp*: int64
    edgeLikedBy*: IgUserEdgeLikedBy
    edgeMediaPreviewLike*: IgUserEdgeMediaPreviewLike
    # location*: NilType
    # nftAssetInfo*: NilType
    thumbnailSrc*: string
    thumbnailResources*: seq[IgUserThumbnailResources]
    # felixProfileGridCrop*: NilType
    coauthorProducers*: seq[IgUserCoauthorProducers]
    # pinnedForUsers*: seq[NilType]
    viewerCanReshare*: bool
    # encodingStatus*: NilType
    isPublished*: bool
    productType*: string
    title*: string
    videoDuration*: float64
  IgUserDimensions* = ref object
    height*: int64
    width*: int64
  IgUserEdgeMediaToTaggedUser* = ref object
    edges*: seq[IgUserEdges2]
  IgUserEdges2* = ref object
    node*: IgUserNode2
  IgUserNode2* = ref object
    user*: IgUserUser2
    x*: float64
    y*: float64
  IgUserUser2* = ref object
    fullName*: string
    followedByViewer*: bool
    id*: string
    isVerified*: bool
    profilePicUrl*: string
    username*: string
  IgUserSharingFrictionInfo* = ref object
    shouldHaveSharingFriction*: bool
    # bloksAppUrl*: NilType
  IgUserOwner* = ref object
    id*: string
    username*: string
  IgUserDashInfo* = ref object
    isDashEligible*: bool
    # videoDashManifest*: NilType
    numberOfQualities*: int64
  IgUserEdgeMediaToCaption* = ref object
    edges*: seq[IgUserEdges3]
  IgUserEdges3* = ref object
    node*: IgUserNode3
  IgUserNode3* = ref object
    text*: string
  IgUserEdgeMediaToComment* = ref object
    count*: int64
  IgUserEdgeLikedBy* = ref object
    count*: int64
  IgUserEdgeMediaPreviewLike* = ref object
    count*: int64
  IgUserThumbnailResources* = ref object
    src*: string
    configWidth*: int64
    configHeight*: int64
  IgUserCoauthorProducers* = ref object
    id*: string
    isVerified*: bool
    profilePicUrl*: string
    username*: string
  IgUserEdgeOwnerToTimelineMedia* = ref object
    count*: int64
    pageInfo*: IgUserPageInfo2
    edges*: seq[IgUserEdges4]
  IgUserPageInfo2* = ref object
    hasNextPage*: bool
    endCursor*: string
  IgUserEdges4* = ref object
    node*: IgUserNode4
  IgUserNode4* = ref object
    typename*: string
    id*: string
    shortcode*: string
    dimensions*: IgUserDimensions2
    displayUrl*: string
    edgeMediaToTaggedUser*: IgUserEdgeMediaToTaggedUser2
    # factCheckOverallRating*: NilType
    # factCheckInformation*: NilType
    # gatingInfo*: NilType
    sharingFrictionInfo*: IgUserSharingFrictionInfo2
    # mediaOverlayInfo*: NilType
    mediaPreview*: string
    owner*: IgUserOwner2
    isVideo*: bool
    hasUpcomingEvent*: bool
    accessibilityCaption*: string
    edgeMediaToCaption*: IgUserEdgeMediaToCaption2
    edgeMediaToComment*: IgUserEdgeMediaToComment2
    commentsDisabled*: bool
    takenAtTimestamp*: int64
    edgeLikedBy*: IgUserEdgeLikedBy2
    edgeMediaPreviewLike*: IgUserEdgeMediaPreviewLike2
    # location*: NilType
    # nftAssetInfo*: NilType
    thumbnailSrc*: string
    thumbnailResources*: seq[IgUserThumbnailResources2]
    coauthorProducers*: seq[IgUserCoauthorProducers2]
    pinnedForUsers*: seq[IgUserPinnedForUsers]
    viewerCanReshare*: bool
    edgeSidecarToChildren*: IgUserEdgeSidecarToChildren
  IgUserDimensions2* = ref object
    height*: int64
    width*: int64
  IgUserEdgeMediaToTaggedUser2* = ref object
    edges*: seq[IgUserEdges5]
  IgUserEdges5* = ref object
    node*: IgUserNode2
  IgUserSharingFrictionInfo2* = ref object
    shouldHaveSharingFriction*: bool
    # bloksAppUrl*: NilType
  IgUserOwner2* = ref object
    id*: string
    username*: string
  IgUserEdgeMediaToCaption2* = ref object
    edges*: seq[IgUserEdges5]
  IgUserNode5* = ref object
    text*: string
  IgUserEdgeMediaToComment2* = ref object
    count*: int64
  IgUserEdgeLikedBy2* = ref object
    count*: int64
  IgUserEdgeMediaPreviewLike2* = ref object
    count*: int64
  IgUserCoauthorProducers2* = ref object
    id*: string
    isVerified*: bool
    profilePicUrl*: string
    username*: string
  IgUserEdgeSidecarToChildren* = ref object
    edges*: seq[IgUserEdges7]
  IgUserEdges7* = ref object
    node*: IgUserNode7
  IgUserNode7* = ref object
    typename*: string
    id*: string
    shortcode*: string
    dimensions*: IgUserDimensions3
    displayUrl*: string
    edgeMediaToTaggedUser*: IgUserEdgeMediaToTaggedUser3
    # factCheckOverallRating*: NilType
    # factCheckInformation*: NilType
    # gatingInfo*: NilType
    sharingFrictionInfo*: IgUserSharingFrictionInfo3
    # mediaOverlayInfo*: NilType
    mediaPreview*: string
    owner*: IgUserOwner2
    isVideo*: bool
    hasUpcomingEvent*: bool
    accessibilityCaption*: string
  IgUserSharingFrictionInfo3* = ref object
    shouldHaveSharingFriction*: bool
    # bloksAppUrl*: NilType
  IgUserDimensions3* = ref object
    height*: int64
    width*: int64
  IgUserEdgeMediaToTaggedUser3* = ref object
    edges*: seq[IgUserEdges2]
  IgUserEdges8* = ref object
    node*: IgUserNode5
  IgUserThumbnailResources2* = ref object
    src*: string
    configWidth*: int64
    configHeight*: int64
  IgUserPinnedForUsers* = ref object
    id*: string
    isVerified*: bool
    profilePicUrl*: string
    username*: string
  IgUserEdgeSavedMedia* = ref object
    count*: int64
    pageInfo*: IgUserPageInfo3
    # edges*: seq[NilType]
  IgUserPageInfo3* = ref object
    hasNextPage*: bool
    # endCursor*: NilType
  IgUserEdgeMediaCollections* = ref object
    count*: int64
    pageInfo*: IgUserPageInfo4
    # edges*: seq[NilType]
  IgUserPageInfo4* = ref object
    hasNextPage*: bool
    # endCursor*: NilType
  IgUserEdgeRelatedProfiles* = ref object
    edges*: seq[IgUserEdges6]
  IgUserEdges6* = ref object
    node*: IgUserNode6
  IgUserNode6* = ref object
    id*: string
    fullName*: string
    isPrivate*: bool
    isVerified*: bool
    profilePicUrl*: string
    username*: string
