# Generated by https://github.com/jiro4989/nimjson

type
  # NilType* = ref object
  Response* = ref object
    data*: Data
    status*: string
  Data* = ref object
    user*: User
  User* = ref object
    biography*: string
    bioLinks*: seq[BioLinks]
    # fbProfileBiolink*: NilType
    biographyWithEntities*: BiographyWithEntities
    blockedByViewer*: bool
    restrictedByViewer*: bool
    countryBlock*: bool
    eimuId*: string
    externalUrl*: string
    # externalUrlLinkshimmed*: string
    edgeFollowedBy*: EdgeFollowedBy
    fbid*: string
    followedByViewer*: bool
    edgeFollow*: EdgeFollow
    followsViewer*: bool
    fullName*: string
    # groupMetadata*: NilType
    hasArEffects*: bool
    hasClips*: bool
    hasGuides*: bool
    hasChannel*: bool
    hasBlockedViewer*: bool
    highlightReelCount*: int64
    hasRequestedViewer*: bool
    hideLikeAndViewCounts*: bool
    id*: string
    isBusinessAccount*: bool
    isProfessionalAccount*: bool
    isSupervisionEnabled*: bool
    isGuardianOfViewer*: bool
    isSupervisedByViewer*: bool
    isSupervisedUser*: bool
    isEmbedsDisabled*: bool
    isJoinedRecently*: bool
    # guardianId*: NilType
    # businessAddressJson*: NilType
    businessContactMethod*: string
    # businessEmail*: NilType
    # businessPhoneNumber*: NilType
    businessCategoryName*: string
    # overallCategoryName*: NilType
    categoryEnum*: string
    categoryName*: string
    isPrivate*: bool
    isVerified*: bool
    isVerifiedByMv4b*: bool
    isRegulatedC18*: bool
    edgeMutualFollowedBy*: EdgeMutualFollowedBy
    pinnedChannelsListCount*: int64
    profilePicUrl*: string
    profilePicUrlHd*: string
    requestedByViewer*: bool
    shouldShowCategory*: bool
    shouldShowPublicContacts*: bool
    showAccountTransparencyDetails*: bool
    # transparencyLabel*: NilType
    transparencyProduct*: string
    username*: string
    connectedFbPage*: string # Not sure
    # pronouns*: seq[NilType]
    edgeFelixVideoTimeline*: EdgeFelixVideoTimeline
    edgeOwnerToTimelineMedia*: EdgeOwnerToTimelineMedia
    edgeSavedMedia*: EdgeSavedMedia
    edgeMediaCollections*: EdgeMediaCollections
    edgeRelatedProfiles*: EdgeRelatedProfiles
  BioLinks* = ref object
    title*: string
    lynxUrl*: string
    url*: string
    linkType*: string
  BiographyWithEntities* = ref object
    rawText*: string
    # entities*: seq[NilType]
  EdgeFollowedBy* = ref object
    count*: int64
  EdgeFollow* = ref object
    count*: int64
  EdgeMutualFollowedBy* = ref object
    count*: int64
    # edges*: seq[NilType]
  EdgeFelixVideoTimeline* = ref object
    count*: int64
    pageInfo*: PageInfo
    edges*: seq[Edges] ## Posts
  PageInfo* = ref object
    hasNextPage*: bool
    endCursor*: string
  Edges* = ref object
    node*: Node
  Node* = ref object
    typename*: string
    id*: string
    shortcode*: string
    dimensions*: Dimensions
    displayUrl*: string
    edgeMediaToTaggedUser*: EdgeMediaToTaggedUser
    # factCheckOverallRating*: NilType
    # factCheckInformation*: NilType
    # gatingInfo*: NilType
    sharingFrictionInfo*: SharingFrictionInfo
    # mediaOverlayInfo*: NilType
    mediaPreview*: string
    owner*: Owner
    isVideo*: bool
    hasUpcomingEvent*: bool
    # accessibilityCaption*: NilType
    dashInfo*: DashInfo
    hasAudio*: bool
    trackingToken*: string
    videoUrl*: string
    videoViewCount*: int64
    edgeMediaToCaption*: EdgeMediaToCaption
    edgeMediaToComment*: EdgeMediaToComment
    commentsDisabled*: bool
    takenAtTimestamp*: int64
    edgeLikedBy*: EdgeLikedBy
    edgeMediaPreviewLike*: EdgeMediaPreviewLike
    # location*: NilType
    # nftAssetInfo*: NilType
    thumbnailSrc*: string
    thumbnailResources*: seq[ThumbnailResources]
    # felixProfileGridCrop*: NilType
    coauthorProducers*: seq[CoauthorProducers]
    # pinnedForUsers*: seq[NilType]
    viewerCanReshare*: bool
    # encodingStatus*: NilType
    isPublished*: bool
    productType*: string
    title*: string
    videoDuration*: float64
  Dimensions* = ref object
    height*: int64
    width*: int64
  EdgeMediaToTaggedUser* = ref object
    edges*: seq[Edges2]
  Edges2* = ref object
    node*: Node2
  Node2* = ref object
    user*: User2
    x*: float64
    y*: float64
  User2* = ref object
    fullName*: string
    followedByViewer*: bool
    id*: string
    isVerified*: bool
    profilePicUrl*: string
    username*: string
  SharingFrictionInfo* = ref object
    shouldHaveSharingFriction*: bool
    # bloksAppUrl*: NilType
  Owner* = ref object
    id*: string
    username*: string
  DashInfo* = ref object
    isDashEligible*: bool
    # videoDashManifest*: NilType
    numberOfQualities*: int64
  EdgeMediaToCaption* = ref object
    edges*: seq[Edges3]
  Edges3* = ref object
    node*: Node3
  Node3* = ref object
    text*: string
  EdgeMediaToComment* = ref object
    count*: int64
  EdgeLikedBy* = ref object
    count*: int64
  EdgeMediaPreviewLike* = ref object
    count*: int64
  ThumbnailResources* = ref object
    src*: string
    configWidth*: int64
    configHeight*: int64
  CoauthorProducers* = ref object
    id*: string
    isVerified*: bool
    profilePicUrl*: string
    username*: string
  EdgeOwnerToTimelineMedia* = ref object
    count*: int64
    pageInfo*: PageInfo2
    edges*: seq[Edges4]
  PageInfo2* = ref object
    hasNextPage*: bool
    endCursor*: string
  Edges4* = ref object
    node*: Node4
  Node4* = ref object
    typename*: string
    id*: string
    shortcode*: string
    dimensions*: Dimensions2
    displayUrl*: string
    edgeMediaToTaggedUser*: EdgeMediaToTaggedUser2
    # factCheckOverallRating*: NilType
    # factCheckInformation*: NilType
    # gatingInfo*: NilType
    sharingFrictionInfo*: SharingFrictionInfo2
    # mediaOverlayInfo*: NilType
    mediaPreview*: string
    owner*: Owner2
    isVideo*: bool
    hasUpcomingEvent*: bool
    accessibilityCaption*: string
    edgeMediaToCaption*: EdgeMediaToCaption2
    edgeMediaToComment*: EdgeMediaToComment2
    commentsDisabled*: bool
    takenAtTimestamp*: int64
    edgeLikedBy*: EdgeLikedBy2
    edgeMediaPreviewLike*: EdgeMediaPreviewLike2
    # location*: NilType
    # nftAssetInfo*: NilType
    thumbnailSrc*: string
    thumbnailResources*: seq[ThumbnailResources2]
    coauthorProducers*: seq[CoauthorProducers2]
    pinnedForUsers*: seq[PinnedForUsers]
    viewerCanReshare*: bool
    edgeSidecarToChildren*: EdgeSidecarToChildren
  Dimensions2* = ref object
    height*: int64
    width*: int64
  EdgeMediaToTaggedUser2* = ref object
    edges*: seq[Edges5]
  Edges5* = ref object
    node*: Node2
  SharingFrictionInfo2* = ref object
    shouldHaveSharingFriction*: bool
    # bloksAppUrl*: NilType
  Owner2* = ref object
    id*: string
    username*: string
  EdgeMediaToCaption2* = ref object  
    edges*: seq[Edges5]
  Node5* = ref object
    text*: string
  EdgeMediaToComment2* = ref object
    count*: int64
  EdgeLikedBy2* = ref object
    count*: int64
  EdgeMediaPreviewLike2* = ref object
    count*: int64
  CoauthorProducers2* = ref object
    id*: string
    isVerified*: bool
    profilePicUrl*: string
    username*: string
  EdgeSidecarToChildren* = ref object
    edges*: seq[Edges7]
  Edges7* = ref object
    node*: Node7
  Node7* = ref object
    typename*: string
    id*: string
    shortcode*: string
    dimensions*: Dimensions3
    displayUrl*: string
    edgeMediaToTaggedUser*: EdgeMediaToTaggedUser3
    # factCheckOverallRating*: NilType
    # factCheckInformation*: NilType
    # gatingInfo*: NilType
    sharingFrictionInfo*: SharingFrictionInfo3
    # mediaOverlayInfo*: NilType
    mediaPreview*: string
    owner*: Owner2
    isVideo*: bool
    hasUpcomingEvent*: bool
    accessibilityCaption*: string
  SharingFrictionInfo3* = ref object
    shouldHaveSharingFriction*: bool
    # bloksAppUrl*: NilType
  Dimensions3* = ref object
    height*: int64
    width*: int64
  EdgeMediaToTaggedUser3* = ref object
    edges*: seq[Edges2]
  Edges8* = ref object
    node*: Node5
  ThumbnailResources2* = ref object
    src*: string
    configWidth*: int64
    configHeight*: int64
  PinnedForUsers* = ref object
    id*: string
    isVerified*: bool
    profilePicUrl*: string
    username*: string
  EdgeSavedMedia* = ref object
    count*: int64
    pageInfo*: PageInfo3
    # edges*: seq[NilType]
  PageInfo3* = ref object
    hasNextPage*: bool
    # endCursor*: NilType
  EdgeMediaCollections* = ref object
    count*: int64
    pageInfo*: PageInfo4
    # edges*: seq[NilType]
  PageInfo4* = ref object
    hasNextPage*: bool
    # endCursor*: NilType
  EdgeRelatedProfiles* = ref object
    edges*: seq[Edges6]
  Edges6* = ref object
    node*: Node6
  Node6* = ref object
    id*: string
    fullName*: string
    isPrivate*: bool
    isVerified*: bool
    profilePicUrl*: string
    username*: string
