# @prompt cookies
GET https://www.instagram.com/api/v1/media/3175699152650296287/comments/?can_support_threading=true&permalink_enabled=false HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0
X-IG-App-ID: 936619743392459
X-Requested-With: XMLHttpRequest
Referer: https://www.instagram.com/p/CwSWY3DOtvf/
Cookie: {{cookies}}
