GET https://www.instagram.com HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0
X-IG-App-ID: 936619743392459
Referer: https://www.instagram.com/

###

GET https://www.instagram.com/api/v1/web/get_ruling_for_content/?content_type=PROFILE&target_id=31993835336 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0
X-IG-App-ID: 936619743392459
X-Requested-With: XMLHttpRequest
Alt-Used: www.instagram.com
Referer: https://www.instagram.com/

###
# @prompt cookies
GET https://www.instagram.com/api/v1/users/web_profile_info/?username=microsoft HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0
X-IG-App-ID: 936619743392459
X-Requested-With: XMLHttpRequest
Alt-Used: www.instagram.com
Referer: https://www.instagram.com/
Cookie: {{cookies}}
