# @prompt cookies
GET https://www.instagram.com/api/v1/feed/user/microsoft/username/?count=12 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0
X-IG-App-ID: 936619743392459
X-Requested-With: XMLHttpRequest
Alt-Used: www.instagram.com
Referer: https://www.instagram.com/microsoft/
Cookie: {{cookies}}

###
# @prompt cookies
GET https://www.instagram.com/api/v1/feed/user/524549267/?count=12&max_id=3167236018158289569_524549267 HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0
X-IG-App-ID: 936619743392459
X-Requested-With: XMLHttpRequest
Alt-Used: www.instagram.com
Referer: https://www.instagram.com/microsoft/
Cookie: {{cookies}}
