# @prompt cookies
# @prompt csrf
POST https://www.instagram.com/api/v1/friendships/destroy/524549267/ HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0
X-CSRFToken: {{csrf}}
X-IG-App-ID: 936619743392459
X-Requested-With: XMLHttpRequest
Origin: https://www.instagram.com
Referer: https://www.instagram.com/
Cookie: {{cookies}}

container_module=profile&nav_chain=PolarisProfileRoot%3AprofilePage%3A1%3Avia_cold_start&user_id=524549267
