# @prompt cookies
# @prompt csrf
POST https://www.instagram.com/api/v1/web/likes/3182352174481337412/unlike/ HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/2010010Firefox/115.0' 
X-CSRFToken: {{csrf}}
X-IG-App-ID: 936619743392459
Content-Type: application/x-www-form-urlencoded
X-Requested-With: XMLHttpRequest
Referer: https://www.instagram.com/
Cookie: {{cookies}}
